[package]
name = "eink_utils"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "eink_utils"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.36.2"
image = "0.25.6"
dither-lib = { git = "https://gitlab.com/efronlicht/dither.git" }
